# Generated by Django 5.1.4 on 2025-01-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
